apiVersion: apps/v1
kind: Deployment
metadata: 
  name: {{ .Values.deployment.name }}
  namespace: {{ .Values.namespace }}
  # labels:
  #   chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  selector:
    matchLabels:
      app: {{ .Values.deployment.name }}
  replicas: {{ default 1 .Values.deployment.replicas | int }}
  template:
    metadata:
      labels:
        app: {{ .Values.deployment.name }}
    spec:
      containers:
      - name: {{ .Values.deployment.name }}
        image: "{{ .Values.deployment.container.image }}:dev-{{ .Values.deployment.version }}"
        