language: go

go:
 - "1.13"

jobs:
  include:
    - stage: build
      script: make build
    - stage: test
      script: make test
    - stage: release
      if: branch = master AND tag IS present
      script:
        - curl -sfL https://install.goreleaser.com/github.com/goreleaser/goreleaser.sh | sh
        - ./bin/goreleaser
      



  
