language: go

go:
 - "1.13"
      
stages:
 - build
 - test
 - name: release
   if: tag IS present
   

jobs:
  include:
    - stage: build
      script: make build
    - stage: test
      script: make test
    - stage: release
      script:
        - curl -sfL https://install.goreleaser.com/github.com/goreleaser/goreleaser.sh | sh
        - ./bin/goreleaser



  
