name: "pack"
version: "0.0.1"
description: "Inject values during helm package"
command: "$HELM_PLUGIN_DIR/bin/helmpack"
hooks:
  install: "cd $HELM_PLUGIN_DIR; scripts/install_plugin.sh"
  update: "cd $HELM_PLUGIN_DIR; scripts/install_plugin.sh"
